M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2025-07-19T12:09:04+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-19T12:09:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X163.5Y-56.0
X163.5Y-113.0
X230.5Y-56.0
X230.5Y-113.0
M30
